# Generated by Django 5.0.2 on 2024-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_food',
        ),
    ]
