# Generated by Django 5.0.2 on 2024-03-08 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0003_tbl_admin'),
        ('Guest', '0008_remove_tbl_restaurant_rest_gender_and_more'),
        ('Restaurant', '0002_delete_tbl_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_photo', models.FileField(upload_to='Assets/FoodImage/')),
                ('food_price', models.CharField(max_length=50)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('foodtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_foodtype')),
                ('rest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_restaurant')),
            ],
        ),
    ]
