# Generated by Django 5.0.2 on 2024-02-20 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryboy_name', models.CharField(max_length=20)),
                ('deliveryboy_email', models.EmailField(max_length=50)),
                ('deliveryboy_address', models.TextField(max_length=100)),
                ('deliveryboy_DOB', models.CharField(max_length=50, null=True)),
                ('deliveryboy_gender', models.CharField(max_length=50)),
                ('deliveryboy_password', models.CharField(max_length=20)),
                ('deliveryboy_photo', models.FileField(upload_to='userdocs/')),
                ('deliveryboy_licence', models.FileField(upload_to='userdocs/')),
                ('deliveryboy_contact', models.IntegerField(null=True)),
                ('deliveryboy_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=20)),
                ('restaurant_contact', models.IntegerField(null=True)),
                ('restaurant_email', models.EmailField(max_length=50)),
                ('restaurant_address', models.TextField(max_length=50)),
                ('restaurant_logo', models.FileField(upload_to='userdocs/')),
                ('restaurant_proof', models.FileField(upload_to='userdocs/')),
                ('restaurant_password', models.CharField(max_length=20)),
                ('restaurant_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_userregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_contact', models.IntegerField(null=True)),
                ('user_Email', models.EmailField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_address', models.TextField(max_length=50)),
                ('user_photo', models.FileField(upload_to='userdocs/')),
                ('user_proof', models.FileField(upload_to='userdocs/')),
                ('user_password', models.CharField(max_length=20)),
                ('user_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
