# Generated by Django 5.0.2 on 2024-03-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_remove_tbl_restaurant_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
