# Generated by Django 5.0.2 on 2024-03-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
