# Generated by Django 5.0.2 on 2024-03-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_deliveryboy_tbl_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_restaurant',
            name='rest_gender',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_photo',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_proof',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_status',
        ),
    ]
