# Generated by Django 5.0.2 on 2024-03-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_page',
        ),
    ]
