# Generated by Django 5.0.2 on 2024-03-08 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_remove_tbl_restaurant_rest_gender_and_more'),
        ('User', '0005_delete_tbl_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=500)),
                ('page_bio', models.CharField(max_length=500)),
                ('page_doj', models.DateField(auto_now_add=True)),
                ('page_photo', models.FileField(upload_to='Assets/PagePhoto/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
