# Generated by Django 5.0.2 on 2024-03-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_tbl_booking_tbl_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
