# Generated by Django 5.0.2 on 2024-03-09 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_remove_tbl_restaurant_rest_gender_and_more'),
        ('Restaurant', '0003_initial'),
        ('User', '0012_remove_tbl_cart_booking_remove_tbl_cart_food_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_amount', models.CharField(max_length=50)),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('booking_status', models.IntegerField(default='0')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_deliveryboy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.CharField(max_length=50)),
                ('cart_status', models.IntegerField(default='0')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_booking')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurant.tbl_food')),
            ],
        ),
    ]
