# Generated by Django 5.0.4 on 2024-04-17 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_tbl_booking_user_remove_tbl_complaint_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_booking',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='tbl_cart',
            name='food',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_page',
        ),
        migrations.DeleteModel(
            name='tbl_post',
        ),
        migrations.DeleteModel(
            name='tbl_booking',
        ),
        migrations.DeleteModel(
            name='tbl_cart',
        ),
    ]
